name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Upgrade Maven to Latest Version
        run: |
          curl -sSL "https://archive.apache.org/dist/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz" | tar xz
          sudo rm -rf /usr/share/maven
          sudo mv apache-maven-3.8.5 /usr/share/maven
          sudo update-alternatives --quiet --install /usr/bin/mvn mvn /usr/share/maven/bin/mvn 20000
          mvn -version

      - name: Build with Maven
        run: mvn -B clean install

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Check GPG Version
        run: gpg --version

      - name: Install Terraform
        run: |
          # Download and install Terraform
          curl -o /tmp/terraform.zip -L https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
          sudo unzip -o /tmp/terraform.zip -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/terraform
          rm /tmp/terraform.zip

      - name: List Files in Terraform Directory
        run: |
          ls ../../testaws/
          

      - name: Terraform Init
        run: |
          # Change to your Terraform directory
          cd ../../testaws/

          # Initialize Terraform
          terraform init


      - name: Terraform Apply
        run: |
          # Apply Terraform changes (replace with your specific options)
          terraform apply -auto-approve
