name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Upgrade Maven to Latest Version
        run: |
          curl -sSL "https://archive.apache.org/dist/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz" | tar xz
          sudo rm -rf /usr/share/maven
          sudo mv apache-maven-3.8.5 /usr/share/maven
          sudo update-alternatives --quiet --install /usr/bin/mvn mvn /usr/share/maven/bin/mvn 20000
          mvn -version

      - name: Build with Maven
        run: mvn -B clean install

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Install Terraform
        run: |
          # Install Terraform
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/gpg
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/gpg-agent
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/gpg-connect-agent
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/gpgconf
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/gpgparsemail
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/gpgsplit
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/gpgv
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/gpgv2
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/gpgv3
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/gpgsm
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/gpgtar
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/gpgv
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/gpgv2
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/gpgv3
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/gpgsm
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/gpgtar
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/packer
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/vault
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/local/bin/terraform

          sudo chmod +x /usr/local/bin/terraform

      - name: Terraform Init
        run: |
          # Change to your Terraform directory
          cd testaws

          # Initialize Terraform
          terraform init

      - name: Terraform Apply
        run: |
          # Change to your Terraform directory
          cd testaws

          # Apply Terraform changes (replace with your specific options)
          terraform apply -auto-approve
